#!/bin/bash

time=$(date +%Y-%m-%d_%H:%M:%S)
dir="$HOME/Pictures/Screenshots"
file="Screenshot_${time}.png"
active_win_area=$(hyprctl -j activewindow | jq -r '[ ( [ .at[0], .at[1]] | join(",") ), ([ .size[0], .size[1]] | join("x") )] | join(" ") ')

# notify
notify_user() {
	if [[ -e "$dir/$file" ]]; then
		dunstify "Saved as ${dir}/${file}"
	else
		dunstify "Screenshot Deleted."
	fi
}

# take shots
shotnow() {
	cd ${dir} && grim $file && swayimg ${dir}/$file
	notify_user
}

shotarea() {
	cd ${dir} && grim -g "$(slurp)" $file && swayimg ${dir}/$file
	notify_user
}

shotwin() {
	cd ${dir} && grim -g "${active_win_area}" $file && swayimg ${dir}/$file
	notify_user
}

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

val=$(printf "1.Screen\n2.Area\n3.Window" | rofi -dmenu -no-custom -l 3 -p 'Screenshot :')

case "$val" in
"1.Screen")
	sleep 1 && shotnow
	;;
"2.Area")
	sleep 1 && shotarea
	;;
"3.Window")
	sleep 1 && shotwin
	;;
*)
	exit 0
	;;
esac

exit 0
