#!/bin/bash
eww="$HOME/.local/bin/eww"

if [[ $1 == "daemon" ]]; then
	$eww daemon
fi

if [[ $1 == "control-center" ]]; then
  $eww close control-center || $eww open control-center
fi

if [[ $1 == "powermenu" ]]; then
  $eww close powermenu || $eww open powermenu
fi
